(()=>{
const API_URL='/api/chat';
const css=`#aiMartBtn{position:fixed;right:18px;bottom:86px;z-index:9998;border:1px solid rgba(212,182,107,.55);border-radius:999px;background:linear-gradient(135deg,#151515,#080808);color:#f4d98a;padding:12px 16px;font-weight:800;box-shadow:0 12px 35px rgba(0,0,0,.45);cursor:pointer}#aiMartPanel{position:fixed;right:18px;bottom:145px;width:min(380px,calc(100vw - 36px));height:min(570px,calc(100vh - 180px));z-index:9999;display:none;flex-direction:column;overflow:hidden;border:1px solid rgba(212,182,107,.35);border-radius:22px;background:#090909;color:#eee;box-shadow:0 25px 70px rgba(0,0,0,.6)}#aiMartPanel.show{display:flex}.ai-head{padding:17px 18px;border-bottom:1px solid rgba(255,255,255,.08);background:linear-gradient(135deg,#161616,#0a0a0a)}.ai-head b{display:block;color:#f4d98a;font-size:17px}.ai-head small{color:#aaa}.ai-close{float:right;border:0;background:none;color:#aaa;font-size:22px;cursor:pointer}.ai-msgs{flex:1;overflow:auto;padding:16px}.ai-msg{max-width:88%;padding:10px 12px;margin:0 0 10px;border-radius:14px;line-height:1.45;font-size:14px;white-space:pre-wrap}.ai-msg.bot{background:#151515;border:1px solid rgba(255,255,255,.07)}.ai-msg.user{margin-left:auto;background:#b99245;color:#090909}.ai-quick{display:flex;gap:7px;overflow:auto;padding:0 12px 10px}.ai-quick button{white-space:nowrap;border:1px solid rgba(212,182,107,.25);background:#111;color:#e9d49b;border-radius:999px;padding:7px 10px;cursor:pointer}.ai-form{display:flex;gap:8px;padding:12px;border-top:1px solid rgba(255,255,255,.08)}.ai-form input{flex:1;min-width:0;border:1px solid #333;border-radius:12px;background:#121212;color:#fff;padding:11px}.ai-form button{border:0;border-radius:12px;background:#d0ad63;color:#080808;font-weight:800;padding:0 15px;cursor:pointer}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const btn=document.createElement('button');btn.id='aiMartBtn';btn.type='button';btn.textContent='🤖 Tanya AI';
const panel=document.createElement('section');panel.id='aiMartPanel';panel.innerHTML=`<div class="ai-head"><button class="ai-close" type="button" aria-label="Tutup">×</button><b>27 Mart AI · Grok</b><small>Bantu cari produk & kebutuhan</small></div><div class="ai-msgs"><div class="ai-msg bot">Halo 👋 Saya siap membantu mencari produk, pembayaran, atau kebutuhan belanja di 27 Mart.</div></div><div class="ai-quick"><button>Top up DANA</button><button>Pulsa murah</button><button>Paket data</button><button>PLN & WiFi</button></div><form class="ai-form"><input maxlength="2000" placeholder="Tanya sesuatu…" autocomplete="off"><button>Kirim</button></form>`;
document.body.append(btn,panel);
const msgs=panel.querySelector('.ai-msgs'),input=panel.querySelector('input'),form=panel.querySelector('form');
const context=()=>Array.from(document.querySelectorAll('.provider-card')).slice(0,12).map(c=>{const b=c.querySelector('.provider-copy b')?.textContent||'';const rows=Array.from(c.querySelectorAll('.product-row')).slice(0,8).map(r=>r.textContent.replace(/\s+/g,' ').trim()).join(' | ');return `${b}: ${rows}`}).join('\n');
const add=(text,who)=>{const d=document.createElement('div');d.className=`ai-msg ${who}`;d.textContent=text;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight};
const ask=async text=>{text=text.trim();if(!text)return;add(text,'user');input.value='';add('Sedang mencari jawaban…','bot');const loading=msgs.lastElementChild;try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,context:context()})});const d=await r.json();loading.remove();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);add(d.text||'Belum ada jawaban.','bot')}catch(e){loading.remove();add('AI belum bisa menjawab saat ini. Coba lagi sebentar.','bot');console.error('27 Mart AI:',e)}};
btn.onclick=()=>{panel.classList.toggle('show');if(panel.classList.contains('show'))input.focus()};panel.querySelector('.ai-close').onclick=()=>panel.classList.remove('show');form.onsubmit=e=>{e.preventDefault();ask(input.value)};panel.querySelectorAll('.ai-quick button').forEach(b=>b.onclick=()=>ask(b.textContent));
})();
