const rupiah=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
const products={1:['Bawang Merah',18000,'500 g'],2:['Tomat Merah',12000,'500 g'],3:['Kentang',16000,'1 kg'],4:['Cabai Merah',22000,'250 g'],5:['Beras Premium',78000,'5 kg'],6:['Minyak Goreng',19000,'1 L'],7:['Gula Pasir',18000,'1 kg'],8:['Tepung Terigu',14000,'1 kg'],9:['Pulsa Telkomsel',12000,'Rp10.000'],10:['Pulsa IM3',12000,'Rp10.000'],11:['Paket Data Telkomsel',15000,'5 GB'],12:['Paket Data XL',17000,'5 GB'],13:['Top Up DANA',22000,'Rp20.000'],14:['Top Up GoPay',22000,'Rp20.000'],15:['Top Up OVO',22000,'Rp20.000'],16:['Token PLN',52000,'Rp50.000'],17:['Tagihan PDAM',5000,'Admin'],18:['Tagihan BPJS',5000,'Admin']};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let order={};try{order=JSON.parse(sessionStorage.getItem('27mart-order')||'{}')}catch{}
const cart=Array.isArray(order.cart)?order.cart:[];
const total=cart.reduce((sum,row)=>sum+(products[row.id]?.[1]||0)*row.qty,0);
document.querySelector('#orderId').textContent=order.orderId||'-';
document.querySelector('#orderCount').textContent=`${cart.reduce((s,x)=>s+x.qty,0)} item`;
document.querySelector('#orderTotal').textContent=rupiah(total);
document.querySelector('#orderItems').innerHTML=cart.length?cart.map(row=>{const p=products[row.id]||['Produk',0,''];return `<div class="order-line"><div><strong>${esc(p[0])}</strong><small>${esc(p[2])} · x${row.qty}</small></div><b>${rupiah(p[1]*row.qty)}</b></div>`}).join(''):'<div class="order-empty">Pesanan tidak ditemukan. Silakan kembali ke katalog.</div>';
const summary=[];if(order.name)summary.push(`<span><b>Nama</b>${esc(order.name)}</span>`);if(order.phone)summary.push(`<span><b>WhatsApp</b>${esc(order.phone)}</span>`);if(order.payment)summary.push(`<span><b>Metode</b>${esc(order.payment)}</span>`);document.querySelector('#customerSummary').innerHTML=summary.join('');
document.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(btn.dataset.copy);const old=btn.textContent;btn.textContent='Tersalin ✓';setTimeout(()=>btn.textContent=old,1400)}catch{alert('Nomor: '+btn.dataset.copy)}}));
document.querySelector('#confirmPayment').addEventListener('click',()=>{if(!cart.length){alert('Pesanan tidak ditemukan. Silakan kembali ke katalog.');return}try{const orders=JSON.parse(localStorage.getItem('27mart-orders')||'[]');const i=orders.findIndex(x=>x.orderId===order.orderId);if(i>=0){orders[i].status='Menunggu verifikasi';orders[i].paidAt=new Date().toISOString();localStorage.setItem('27mart-orders',JSON.stringify(orders))}}catch{}const lines=cart.map(row=>{const p=products[row.id]||['Produk',0,''];return `• ${p[0]} (${p[2]}) x${row.qty} = ${rupiah(p[1]*row.qty)}`});const msg=['Halo 27 Mart 👋',`Konfirmasi pembayaran pesanan ${order.orderId||'-'}:`,'',`Nama: ${order.name||'-'}`,`WhatsApp: ${order.phone||'-'}`,...lines,'',`Total: ${rupiah(total)}`,order.payment?`Metode pembayaran: ${order.payment}`:null,order.address?`Alamat: ${order.address}`:null,order.target?`Nomor/ID tujuan: ${order.target}`:null,order.note?`Catatan: ${order.note}`:null,'','Saya sudah melakukan pembayaran. Mohon dicek dan dikonfirmasi. Saya siap mengirim bukti pembayaran jika diperlukan.'].filter(Boolean).join('\n');window.open(`https://wa.me/62816951127?text=${encodeURIComponent(msg)}`,'_blank')});
