-- 27 Mart online order database
-- Run this script once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_code text not null unique,
  customer_name text not null,
  customer_phone text not null,
  target text,
  address text,
  note text,
  payment_method text not null,
  total numeric(12,2) not null default 0,
  status text not null default 'Menunggu pembayaran',
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id integer not null,
  product_name text not null,
  unit text,
  price numeric(12,2) not null,
  qty integer not null check (qty > 0)
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Customers may create an order, but cannot read/update the orders table directly.
drop policy if exists "public can create orders" on public.orders;
create policy "public can create orders"
on public.orders for insert to anon, authenticated
with check (true);

-- Customer order items are accepted only for an order that exists.
drop policy if exists "public can create order items" on public.order_items;
create policy "public can create order items"
on public.order_items for insert to anon, authenticated
with check (exists (select 1 from public.orders o where o.id = order_id));

-- Authenticated admin account can manage orders and items.
drop policy if exists "authenticated can read orders" on public.orders;
create policy "authenticated can read orders"
on public.orders for select to authenticated
using (true);

drop policy if exists "authenticated can update orders" on public.orders;
create policy "authenticated can update orders"
on public.orders for update to authenticated
using (true)
with check (true);

drop policy if exists "authenticated can read order items" on public.order_items;
create policy "authenticated can read order items"
on public.order_items for select to authenticated
using (true);

-- Safe customer lookup: the browser can ask for one exact order code without
-- receiving the whole orders table.
create or replace function public.get_order_status(p_order_code text)
returns table (
  order_code text,
  customer_name text,
  total numeric,
  status text,
  created_at timestamptz,
  paid_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select o.order_code, o.customer_name, o.total, o.status, o.created_at, o.paid_at
  from public.orders o
  where o.order_code = p_order_code
  limit 1;
$$;

grant execute on function public.get_order_status(text) to anon, authenticated;

-- Realtime for the admin dashboard.
do $$
begin
  alter publication supabase_realtime add table public.orders;
exception when duplicate_object then
  null;
end $$;
